### ISSUE TITLE
Project took too long to load.

### ISSUE THREAD

**Issue by Sandile-Dev01** [yashpatel003/FoodHub_App#1]
I reckon the project is good as it is on the Readme but it took too long to load and that is not great for _UX_.

**Comment by yashpatel003** [comment]
It seems like you're experiencing slow loading times, and you suspect there might be an issue with your Babel configuration. Babel is often used to transpile JavaScript code, and its configuration can impact the performance of a project.
Make sure install packages -- npm install --save-dev @babel/core @babel/preset-env
